#!/bin/bash

MESSAGE=$(git log -1 HEAD --pretty=format:%s)
AuthorEmail=$GIT_AUTHOR_EMAIL
Author=$GIT_COMMITTER_NAME
Date=$GIT_COMMITTER_DATE
UniqueSeparator="unique_separator_1_2343fd" s

"C:\Users\viktor.d\Desktop\GitEmailSender\EmailSender\EmailSender\bin\Debug\EmailSender.exe" $MESSAGE $UniqueSeparator $AuthorEmail $UniqueSeparator $Author $UniqueSeparator $Date 